language: perl
sudo: false
matrix:
  include:
    - os: linux
      perl: '5.8'
    - os: linux
      perl: '5.10'
    - os: linux
      perl: '5.28'
    - os: windows
      language: shell
      env: _PREFIX='cmd.exe /x/d/c'
      before_install:
        - choco install strawberryperl
        - export PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH
        - perl -V
script:
  - $_PREFIX prove -l t
