language: perl
sudo: false
matrix:
  include:
    - os: linux
      perl: '5.8'
    - os: linux
      perl: '5.10'
    - os: linux
      perl: '5.28'
    - os: windows
      language: shell
      before_install:
        - choco install strawberryperl
        - export PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH
        - perl -V
        - cpanm -n -v --reinstall TAP::Harness
install:
  - curl -fsSL https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - perl -S prove -l t
