language: perl
sudo: false
matrix:
  include:
    - os: linux
      perl: '5.8'
    - os: linux
      perl: '5.10'
    - os: linux
      perl: '5.28'
    - os: windows
      language: sh
      before_install:
        - choco install strawberryperl
        - export PATH=/c/Strawberry/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:$PATH
        - echo $PATH
        - perl -V
install:
  - echo $PATH
  - which -a curl
  - curl -fsSL https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - echo $PATH
  - prove -l t
