sudo: required
services:
  - docker
before_install:
  - docker pull rakudo-star
  - docker run rakudo-star perl6 -v
script:
  - env
  - docker run -v `pwd`:/app rakudo-star -it bash -c 'cd /app && env'
