language: objective-c
osx_image:
  - xcode9.3beta
  - xcode9.2
  - xcode9.1
  - xcode9.1
  - xcode9
  - xcode8.3
  - xcode8
  - xcode7.3
  - xcode6.4
script:
  - /usr/bin/perl -V
  - curl -o cpanm --compressed -sSL http://cpanmin.us
  - /usr/bin/perl cpanm -V
  - /usr/bin/perl cpanm -l perl5 --self-contained forks || ( cat ~/.cpanm/build.log; false )
  - find perl5 | grep List/MoreUtils
